---
#This YAML file is to modify the user profile in BOTP landscape. 

- hosts: node1 
  remote_user: test
  become: yes
  gather_facts: yes
  vars: 
    user_password: "$PaxUU9LaJ0"

  tasks:
    - name: Add the new users for CommVault
      user:
        name: user_name
        uid: 6000
        create_home: yes
        shell: /bin/bash
        state: present
        update_password: on_create
        password: "{{user_password}}"
      register: user_creation
    - debug: 
        msg: "{{user_creation}}"

    - name: Deleting the existing bkp_user
      user:
        name: bkp_user
        state: absent
        remove: yes
        
    - name: Giving sudo permissions
      lineinfile:
        path: /etc/sudoers
        state: present
        line: 'user_name	        ALL=(ALL)	ALL'
        
    - name: This is to ask user to change the password at login
      shell: "{{item}}"
      with_items:
        - chage -d 0 user_name

