---
# Building a wordpress site through ansible
# Created multiple tasks and running as per the requirment
# Date 14/07/2019

- name: update the server
  yum: 
    name: "*"
    state: latest
  ignore_errors: true

- name: restart system to reboot to newest kernel
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: wait for 10 seconds
  pause:
    seconds: 10

- name: wait for the system to reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 120
