---
- name: mariadb installation 
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - mariadb
    - mariadb-server
    - python2-PyMySQL.noarch
    - python36-PyMySQL.noarch
    - MySQL-python

- name: enable httpd services using systemd
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: copy the script for DB mysql_secure_installation
  copy: 
    src: "{{item}}" 
    dest: /home/test/Desktop/
  with_items:
    - mysql_secure_installation.sh
    - database_creation.sh

- name: Execute the secureinstalaltion code and Database creation code
  shell: ./mysql_secure_installation.sh
  args:
    chdir: /home/test/Desktop/
  ignore_errors: true

- name: Execute the secureinstalaltion code and Database creation code
  shell: ./database_creation.sh
  args:
    chdir: /home/test/Desktop/
  ignore_errors: true
