- name: install php 7.3
  yum:
    name: "{{item}}"
    state: latest
  loop:
    - php
    - php-common
    - php-opcache
    - php-mcrypt
    - php-cli
    - php-gd
    - php-curl
    - php-mysqlnd
    
