---
# Building a wordpress site through ansible
# Created multiple tasks and running as per the requirment
# Date 14/07/2019

- name: install php 7.3
  yum:
    name: "{{item}}"
    state: latest
  loop:
    - php
    - php-common
    - php-opcache
    - php-mcrypt
    - php-cli
    - php-gd
    - php-curl
    - php-mysqlnd
    
